# Generated by Django 5.2.3 on 2025-06-14 04:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 半個室A、完全個室B', max_length=100, verbose_name='スペース名')),
                ('space_type', models.CharField(choices=[('SEMI_PRIVATE', '半個室'), ('PRIVATE', '完全個室')], max_length=20, verbose_name='スペース種別')),
                ('capacity', models.IntegerField(default=1, help_text='通常は1人用', verbose_name='収容人数')),
                ('equipment', models.TextField(help_text='PC、モニター、ヘッドセットなど', verbose_name='設備')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='半個室: 500円、完全個室: 1000円', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='時間単価（円）')),
                ('description', models.TextField(blank=True, help_text='スペースの特徴や利用シーンなど', verbose_name='説明')),
                ('is_available', models.BooleanField(default=True, help_text='メンテナンス時などはFalse', verbose_name='利用可能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'スペース',
                'verbose_name_plural': 'スペース',
                'ordering': ['space_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='予約日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('purpose', models.TextField(blank=True, help_text='会議、作業、学習など', verbose_name='利用目的')),
                ('status', models.CharField(choices=[('CONFIRMED', '確定'), ('CANCELLED', 'キャンセル')], default='CONFIRMED', max_length=20, verbose_name='予約状態')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='利用料金総額（円）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='予約更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.space', verbose_name='スペース')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-reservation_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='支払い金額（円）')),
                ('payment_method', models.CharField(choices=[('CREDIT', 'クレジットカード'), ('QR', 'QR決済'), ('INVOICE', '請求書')], max_length=20, verbose_name='支払い方法')),
                ('payment_status', models.CharField(choices=[('PENDING', '支払い待ち'), ('COMPLETED', '支払い完了'), ('FAILED', '支払い失敗'), ('CANCELLED', 'キャンセル')], default='PENDING', max_length=20, verbose_name='支払い状態')),
                ('transaction_id', models.CharField(blank=True, help_text='決済システムから返される取引ID', max_length=100, null=True, verbose_name='取引ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支払い完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservation.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '支払い',
                'verbose_name_plural': '支払い',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('space', 'reservation_date', 'start_time', 'end_time'), name='unique_confirmed_reservation'),
        ),
    ]
